chore(deps): remove package-lock.json
```
1chooo-com-docs:build: Failed to compile.
1chooo-com-docs:build:
1chooo-com-docs:build: Type error: Cannot find type definition file for 'dompurify'.
1chooo-com-docs:build:   The file is in the program because:
1chooo-com-docs:build:     Entry point for implicit type library 'dompurify'
1chooo-com-docs:build:
1chooo-com-docs:build: npm error Lifecycle script `build` failed with error:
1chooo-com-docs:build: npm error code 1
1chooo-com-docs:build: npm error path /vercel/path0/apps/docs
1chooo-com-docs:build: npm error workspace 1chooo-com-docs@0.3.3
1chooo-com-docs:build: npm error location /vercel/path0/apps/docs
1chooo-com-docs:build: npm error command failed
1chooo-com-docs:build: npm error command sh -c next build
1chooo-com-docs:build: ERROR: command finished with error: command (/vercel/path0/apps/docs) /node20/bin/npm run build exited (1)
1chooo-com-docs#build: command (/vercel/path0/apps/docs) /node20/bin/npm run build exited (1)
  Tasks:    0 successful, 1 total
```